
const data =[
    {
        new:'New',
        name:'iPhone 14 Pro Max',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14promax-digitalmat-gallery-5-202209?wid=364&hei=333&fmt=png-alpha&.v=1660830896850',
        price:1099,
        id:101,
        color1:'deepPurple circle',
        color2:'gold circle',
        color3:'silver circle',
        color4:'graphite circle',
        image1:'https://i.postimg.cc/fbkwNbb4/iphone14-Pro-1.jpg',
        image2:'https://i.postimg.cc/HnKgd8D5/iphone14-Pro-2-1.jpg',
        image3:'https://i.postimg.cc/44FZzq7d/iphone14-Pro-2-2.jpg',
        category:'iPhone',
        stock:10,
        imageCart:'https://i.postimg.cc/VvfrWm6S/iphone14-Pro-Cart.png',
        chipImg:'https://i.postimg.cc/dt6zQcZW/A16-Bionic.png',
        chip:'A16 Bionic',
        screen:"6.7''",
        screenDesc:'All-screen OLED',
        cameraImg:'https://i.postimg.cc/wjBn74h9/Camera-Iphone.png',
        camera:'48 MP | Telephoto, Wide, UltraWide',
        battery:'Up to 29 hours of video playback',

        
        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
        storage4:'1TB',
    },
    {
        new:'New',
        name:'iPhone 14 Pro',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone14pro-202209?wid=340&hei=264&fmt=p-jpg&qlt=95&.v=1661782459247',
        price:999,
        id:102,
        color1:'deepPurple circle',
        color2:'gold circle',
        color3:'silver circle',
        color4:'graphite circle',
        image1:'https://i.postimg.cc/fbkwNbb4/iphone14-Pro-1.jpg',
        image2:'https://i.postimg.cc/HnKgd8D5/iphone14-Pro-2-1.jpg',
        image3:'https://i.postimg.cc/MGGvv0zf/iphone14-Pro-2-2.jpg',
        category:'iPhone',
        stock:10,
        imageCart:'https://i.postimg.cc/VvfrWm6S/iphone14-Pro-Cart.png',

        chipImg:'https://i.postimg.cc/dt6zQcZW/A16-Bionic.png',
        chip:'A16 Bionic',
        screen:"6.1''",
        screenDesc:'Super Retina XDR Display',
        cameraImg:'https://i.postimg.cc/wjBn74h9/Camera-Iphone.png',
        camera:'48 MP | Telephoto, Wide, UltraWide',
        battery:'Up to 29 hours of video playback',


        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
        storage4:'1TB',
    },
    {
        new:'New',
        name:'iPhone 14',
        img:'https://i.postimg.cc/dVKM6tC6/iphone14-Card.jpg',
        price:799,
        id:103,
        color1:'blue circle',
        color2:'purple circle',
        color3:'graphite circle',
        color4:'silver circle',
        color5:'red circle',
        image1:'https://i.postimg.cc/RhwkyP2b/iphone14-1.jpg',
        image2:'https://i.postimg.cc/BvqrWYM1/iphone14-2-1.jpg',
        image3:'https://i.postimg.cc/HkzrYv1C/iphone14-2-2.jpg',
        category:'iPhone',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-purple-select-202209?',
        
        chipImg:'https://i.postimg.cc/63kfpRcx/A15-Bionic.png',
        chip:'A15 Bionic',
        screen:"6.1''",
        screenDesc:'Super Retina XDR Display',
        cameraImg:'https://i.postimg.cc/t4mwPd5W/Camera-Iphone2.png',
        camera:'12 MP | Telephoto, UltraWide',
        battery:'Up to 26 hours of video playback',


        classStorage4:'hide',
        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
    },
    {
        new:'',
        name:'iPhone 13 Pro Max',
        img:'https://i.postimg.cc/528gKQjj/i-Phone13-Pro-Max-Card.jpg',
        price:1099,
        id:201,
        color1:'green circle',
        color2:'silver circle',
        color3:'gold circle',
        color4:'graphite circle',
        color5:'blue circle',
        image1:'https://i.postimg.cc/kMY5Ypd2/iPhone1.jpg',
        image2:'https://i.postimg.cc/HxtLXcWC/Iphone2-1.png',
        image3:'https://i.postimg.cc/cC4Lmx6t/i-Phone2-2.png',
        category:'iPhone',
        stock:10,
        imageCart:'https://i.postimg.cc/fyNSQWVn/i-Phone13-Pro-Cart.png',

        chipImg:'https://i.postimg.cc/63kfpRcx/A15-Bionic.png',
        chip:'A15 Bionic',
        screen:"6.7''",
        screenDesc:'Super Retina XDR Display',
        cameraImg:'https://i.postimg.cc/wjBn74h9/Camera-Iphone.png',
        camera:'12 MP | Telephoto, Wide, UltraWide',
        battery:'Up to 28 hours of video playback',

        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
        storage4:'1TB',
    },
    {
        new:'',
        name:'iPhone 13 Pro',
        img:'https://i.postimg.cc/528gKQjj/i-Phone13-Pro-Max-Card.jpg',
        price:999,
        id:202,
        color1:'green circle',
        color2:'silver circle',
        color3:'gold circle',
        color4:'graphite circle',
        color5:'blue circle',
        image1:'https://i.postimg.cc/kMY5Ypd2/iPhone1.jpg',
        image2:'https://i.postimg.cc/HxtLXcWC/Iphone2-1.png',
        image3:'https://i.postimg.cc/cC4Lmx6t/i-Phone2-2.png',
        category:'iPhone',
        stock:10,
        imageCart:'https://i.postimg.cc/fyNSQWVn/i-Phone13-Pro-Cart.png',

        chipImg:'https://i.postimg.cc/63kfpRcx/A15-Bionic.png',
        chip:'A15 Bionic',
        screen:"6.1''",
        screenDesc:'Super Retina XDR Display',
        cameraImg:'https://i.postimg.cc/wjBn74h9/Camera-Iphone.png',
        camera:'12 MP | Telephoto, Wide, UltraWide',
        battery:'Up to 28 hours of video playback',

        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
        storage4:'1TB',
        
    },
    {
        new:'',
        name:'iPhone 13',
        img:'https://i.postimg.cc/4dpwqKWW/i-Phone13-Card.jpg',
        price:699,
        id:203,
        color1:'green circle',
        color2:'graphite circle',
        color3:'pink circle',
        color4:'blue circle',
        color5:'red circle',
        image1:'https://i.postimg.cc/DfJPzKnP/i-Phone13-1.jpg',
        image2:'https://i.postimg.cc/mDvddv7W/i-Phone13-2-1.jpg',
        image3:'https://i.postimg.cc/LsjN0C4c/i-Phone13-2-2.jpg',
        category:'iPhone',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-green-select?',


        chipImg:'https://i.postimg.cc/63kfpRcx/A15-Bionic.png',
        chip:'A15 Bionic',
        screen:"6.1''",
        screenDesc:'Super Retina XDR Display',
        cameraImg:'https://i.postimg.cc/t4mwPd5W/Camera-Iphone2.png',
        camera:'12 MP | Telephoto, UltraWide',
        battery:'Up to 19 hours of video playback',

        
        classStorage4:'hide',
        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
    },
    {
        new:'',
        name:'iPhone 12',
        img:'https://i.postimg.cc/sxFGxhB7/iphone12-Card.jpg',
        price:599,
        id:301,
        color1:'gold circle',
        color2:'purple circle',
        color3:'blue circle',
        color4:'creamGreen circle',
        color5:'graphite circle',
        color6:'red circle',
        image1:'https://i.postimg.cc/jjpKjQX7/i-Phone12-1.jpg',
        image2:'https://i.postimg.cc/BZzTFjF8/i-Phone12-2-1.jpg',
        image3:'https://i.postimg.cc/kgfctcPx/iphone12-2-2.jpg',
        category:'iPhone',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-blue-select-2020?',

        chipImg:'https://i.postimg.cc/8PwnDfT9/A14-Bionic.png',
        chip:'A14 Bionic',
        screen:"6.1''",
        screenDesc:'Super Retina XDR Display',
        cameraImg:'https://i.postimg.cc/DzJDcWjD/Camera-Iphone2-2.png',
        camera:'12 MP | Telephoto, UltraWide',
        battery:'Up to 17 hours of video playback',

        
        classStorage4:'hide',
        storage1:'64GB',
        storage2:'128GB',
        storage3:'256GB',
    },
    {
        new:'',
        name:'iPhone 12 Mini',
        img:'https://i.postimg.cc/K8YjZN9C/iphone12-Mini-Card.jpg',
        price:499,
        id:302,
        color1:'gold circle',
        color2:'purple circle',
        color3:'blue circle',
        color4:'creamGreen circle',
        color5:'graphite circle',
        color6:'red circle',
        image1:'https://i.postimg.cc/jjpKjQX7/i-Phone12-1.jpg',
        image2:'https://i.postimg.cc/BZzTFjF8/i-Phone12-2-1.jpg',
        image3:'https://i.postimg.cc/kgfctcPx/iphone12-2-2.jpg',
        category:'iPhone',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-blue-select-2020?',

        chipImg:'https://i.postimg.cc/8PwnDfT9/A14-Bionic.png',
        chip:'A14 Bionic',
        screen:"5.4''",
        screenDesc:'Super Retina XDR Display',
        cameraImg:'https://i.postimg.cc/DzJDcWjD/Camera-Iphone2-2.png',
        camera:'12 MP | Telephoto, UltraWide',
        battery:'Up to 17 hours of video playback',

        classStorage4:'hide',
        storage1:'64GB',
        storage2:'128GB',
        storage3:'256GB',
    },
    {
        new:'',
        name:'iPhone SE 2022',
        img:'https://i.postimg.cc/G24mkm0K/iphone-SE-Card.jpg',
        price:429,
        id:303,
        color1:'graphite circle',
        color2:'silver circle',
        color3:'red circle',
        image1:'https://i.postimg.cc/8CTMGW2Y/iphone-SE-1.jpg',
        image2:'https://i.postimg.cc/TYWrJTjt/iphone-SE-2-1.jpg',
        image3:'https://i.postimg.cc/t4p1HQf5/iphone-SE-2-2.jpg',
        category:'iPhone',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-midnight-select-202203?',

        chipImg:'https://i.postimg.cc/63kfpRcx/A15-Bionic.png',
        chip:'A15 Bionic',
        screen:"4.7''",
        screenDesc:'Retina HD Display',
        cameraImg:'https://i.postimg.cc/qvRD7BRR/Camera-Iphone-SE.png',
        camera:'12 MP | Telephoto',
        battery:'Up to 15 hours of video playback',

        classStorage4:'hide',
        storage1:'64GB',
        storage2:'128GB',
        storage3:'256GB',
    },
    {
        new:'',
        name:'MacBook Air M1',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-card-40-macbook-air-202110?wid=600&hei=500&fmt=p-jpg&qlt=95&.v=1633726242000',
        price:999,
        id:401,
        color1:'gold circle',
        color2:'silver circle',
        color3:'graphite circle',
        image1:'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/refurb-macbook-air-gold-m1-202010?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1634145607000',
        category:'Mac',
        stock:10,
        imageCart:'https://i.postimg.cc/wjw66qG8/Mac-Air-M1-Cart.jpg',

        chipImg:'https://i.postimg.cc/Y9VSLCNx/M1Chip.png',
        chip:'Apple M1 chip',
        screenImg:'https://i.postimg.cc/yxBF5j55/Screen-Laptop.png',
        screen:"13.3''",
        screenDesc:'Retina Display',
        ram:'16 GB',
        cpu:'8-core',
        gpu:'7-core',
        battery:'18 hrs',

        storage1:'256GB SSD',
        storage2:'512GB SSD ',
        storage3:'1TB SSD',
        storage4:'2TB SSD',
    },
    {
        new:'',
        name:"MacBook Air M2 ",
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-card-40-macbook-air-202206?wid=600&hei=500&fmt=p-jpg&qlt=95&.v=1653499620093',
        price:1199,
        id:402,
        color1:'deepPurple circle',
        color2:'gold circle',
        color3:'graphite circle',
        color4:'gray circle',
        image1:'https://sneakerhousearg.com/wp-content/uploads/2022/06/Apple-WWDC22-MacBook-Air-hero-220606.jpg',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?',

        chipImg:'https://i.postimg.cc/SRMx6bDb/M2Chip.png',
        chip:'Apple M2 chip',
        screenImg:'https://i.postimg.cc/yxBF5j55/Screen-Laptop.png',
        screen:"13.3''",
        screenDesc:'Retina Display',
        ram:'24 GB',
        cpu:'8-core',
        gpu:'10-core',
        battery:'18 hrs',

        classStorage4:'hide',
        storage1:'512GB',
        storage2:'1TB',
        storage3:'2TB',
    },
    {
        new:'',
        name:'MacBook Pro 16”',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-card-40-macbook-pro-14-16-202206?wid=600&hei=500&fmt=p-jpg&qlt=95&.v=1653498040386',
        price:2499,
        id:403,
        color1:'graphite circle',
        color2:'gray circle',
        image1:'https://es.digitaltrends.com/wp-content/uploads/2019/11/apple_16-inch-macbook-pro_111319.jpg?p=1',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-spacegray-select-202110?',

        chipImg:'https://i.postimg.cc/pdf43WLL/intel-1.png',
        chip:'Core i9 processor',
        screenImg:'',
        screen:"16''",
        screenDesc:'Retina Display',
        ram:'64 GB',
        cpu:'8-core',
        gpu:'AMD',
        battery:'11 hrs',

        storage1:'1TB SSD',
        storage2:'2TB SSD ',
        storage3:'4TB SSD',
        storage4:'8TB SSD',
    },
    {
        new:'',
        name:'iMac 24”',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac-24-touch-id-blue-gallery-1?wid=2000&hei=1536&fmt=jpeg&qlt=95&.v=1617486478000',
        price:1299,
        id:501,
        color1:'red circle',
        color2:'blue circle',
        color3:'yellow circle',
        color4:'deepPurple circle',
        color5:'gray circle',
        image1:'https://ar.oneclickstore.com/wp-content/uploads/2021/08/iMac24_2P_SIL_001.jpg',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac-24-blue-selection-hero-202104?',

        chipImg:'https://i.postimg.cc/Y9VSLCNx/M1Chip.png',
        chip:'Apple M1 chip',
        screenImg:'https://i.postimg.cc/cCmQNYGJ/Screen-Monitor.png',
        screen:"24''",
        screenDesc:'4.5K Retina Display',
        ram:'16 GB',
        cpu:'8-core',
        gpu:'8-core',
        battery:'-',

        
        classStorage4:'hide',
        storage1:'512GB',
        storage2:'1TB',
        storage3:'2TB',
    },
    {
        new:'',
        name:'Studio Display',
        img:'https://www.apple.com/v/studio-display/a/images/overview/pairs/hw_screen_studio_display__fsht7mw0rhqq_large.jpg',
        price:1599,
        id:502,
        color1:'gray circle',
        image1:'https://www.apple.com/newsroom/images/product/mac/standard/Apple-Studio-Display-Magic-Trackpad-Keyboard-Mouse-220308_big.jpg.slideshow-xlarge_2x.jpg',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MMYQ3?',
        hide:'hide'
    },
    {
        new:'',
        name:'Pro Display XDR',
        img:'https://i.postimg.cc/VsnfXzYB/Pro-Display-XDR.jpg',
        price:4999,
        id:503,
        color1:'gray circle',
        image1:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/pro-display-gallery1-201909?wid=2000&hei=1536&fmt=jpeg&qlt=95&.v=1574201024213',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/pro-display-hero?',
        hide:'hide'
    },
    {
        new:'',
        name:'Mac Mini',
        img:'https://i.postimg.cc/5NN8Zyvq/MacMini.jpg',
        price:699,
        id:601,
        color1:'gray circle',
        image1:'https://www.macstore.com.pa/ccstore/v1/images/?source=/file/v5051881803036070256/products/Mac-Mini-M1-Gris.jpg',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-hero-202011?',

        chipImg:'https://i.postimg.cc/Y9VSLCNx/M1Chip.png',
        chip:'Apple M1 chip',
        screenImg:'https://i.postimg.cc/cCmQNYGJ/Screen-Monitor.png',
        screen:"-",
        screenDesc:'',
        ram:'16 GB',
        cpu:'8-core',
        gpu:'8-core',
        battery:'-',

        classStorage4:'hide',
        storage1:'512GB',
        storage2:'1TB',
        storage3:'2TB',
    },
    {
        new:'',
        name:'Mac Studio',
        img:'https://i.postimg.cc/cCK0nf2B/Mac-Studio.jpg',
        price:1999,
        id:602,
        color1:'gray circle',
        image1:'https://media.revistagq.com/photos/62289806eb46c38200386be7/master/w_1960,h_1306,c_limit/Apple-Mac-Studio-front-220308.jpg',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-select-202203?',

        chipImg:'https://i.postimg.cc/mZKDbjS1/M1-Ultra-Chip.png',
        chip:'Apple M1 ULTRA chip',
        screenImg:'https://i.postimg.cc/cCmQNYGJ/Screen-Monitor.png',
        screen:"-",
        screenDesc:'',
        ram:'128 GB',
        cpu:'20-core',
        gpu:'64-core',
        battery:'-',

        storage1:'1TB SSD',
        storage2:'2TB SSD ',
        storage3:'4TB SSD',
        storage4:'8TB SSD',
    },
    {
        new:'',
        name:'Mac Pro',
        img:'https://i.postimg.cc/SsCSgGkZ/MacPro.jpg',
        price:5999,
        id:603,
        color1:'gray circle',
        image1:'https://www.macstoreuk.com/wp-content/uploads/2020/07/Mac-Pro.jpg',
        category:'Mac',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-pro-hero-cto?',

        chipImg:'https://i.postimg.cc/pdf43WLL/intel-1.png',
        chip:'Xeon W processor',
        screenImg:'https://i.postimg.cc/cCmQNYGJ/Screen-Monitor.png',
        screen:"-",
        screenDesc:'',
        ram:'768 GB',
        cpu:'28-core',
        gpu:'AMD',
        battery:'11 hrs',

        storage1:'1TB SSD',
        storage2:'2TB SSD ',
        storage3:'4TB SSD',
        storage4:'8TB SSD',
    },
    {
        new:'',
        name:"iPad Pro 12.9'' ",
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipadpro12-digitalmat-gallery-1-202111?wid=364&hei=333&fmt=png-alpha&.v=1635185169000',
        price:1099,
        id:701,
        color1:'gray circle',
        color2:'graphite circle',
        image1:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-12-select-wifi-spacegray-202104_GEO_MX_FMT_WHH?wid=1945&hei=2000&fmt=jpeg&qlt=95&.v=1617923546000',
        category:'iPad',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-12-select-wifi-spacegray-202104?',

        chipImg:'https://i.postimg.cc/Y9VSLCNx/M1Chip.png',
        chip:'M1 Apple chip',
        screen:"12.9''",
        screenDesc:'Liquid Retina XDR Display',
        cameraImg:'https://i.postimg.cc/63d5Q2fJ/Camera-Ipad2.png',
        camera:'12 MP | Telephoto, UltraWide',
        battery:'Up to 10 hours of video playback',
        chargerImg:'https://i.postimg.cc/mgMx4Ngj/Charge-Ipad-Pro.png',
        charger:'USB-C Fast-Charge',

        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
        storage4:'1TB',
    },
    {
        new:'',
        name:"iPad Pro 11'' ",
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipadpro11-digitalmat-gallery-1-202111?wid=364&hei=333&fmt=png-alpha&.v=1635185148000',
        price:799,
        id:702,
        color1:'gray circle',
        color2:'graphite circle',
        image1:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-12-select-wifi-spacegray-202104_GEO_MX_FMT_WHH?wid=1945&hei=2000&fmt=jpeg&qlt=95&.v=1617923546000',
        category:'iPad',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-spacegray-202104?',

        chipImg:'https://i.postimg.cc/Y9VSLCNx/M1Chip.png',
        chip:'M1 Apple chip',
        screen:"11''",
        screenDesc:'Liquid Retina XDR Display',
        cameraImg:'https://i.postimg.cc/63d5Q2fJ/Camera-Ipad2.png',
        camera:'12 MP | Telephoto, UltraWide',
        battery:'Up to 10 hours of video playback',
        chargerImg:'https://i.postimg.cc/mgMx4Ngj/Charge-Ipad-Pro.png',
        charger:'USB-C Fast-Charge',

        storage1:'128GB',
        storage2:'256GB',
        storage3:'512GB',
        storage4:'1TB',
        
    },
    {
        new:'New',
        name:"iPad Air ",
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipadair-digitalmat-gallery-1-202203?wid=364&hei=333&fmt=jpeg&qlt=95&.v=1644962768135',
        price:599,
        id:703,
        color1:'graphite circle',
        color2:'pink circle',
        color3:'blue circle',
        color4:'purple circle',
        color5:'gray circle',
        image1:'https://i.postimg.cc/fWrPd2dv/ipadAir.png',
        category:'iPad',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-wifi-pink-202203?',

        chipImg:'https://i.postimg.cc/Y9VSLCNx/M1Chip.png',
        chip:'M1 Apple chip',
        screen:"10.9''",
        screenDesc:'Liquid Retina Display',
        cameraImg:'https://i.postimg.cc/0Qgyxdm0/Camera-Ipad1.png',
        camera:'12 MP | Telephoto, Wide',
        battery:'Up to 10 hours of video playback',
        chargerImg:'https://i.postimg.cc/vH4FqdRp/Charge-Ipad-Mid.png',
        charger:'USB-C connector',

        classStorage3:'hide',
        classStorage4:'hide',
        storage1:'64GB',
        storage2:'128GB',

    },
    {
        new:'',
        name:"iPad",
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-card-40-ipad-202109?wid=400&hei=500&fmt=p-jpg&qlt=95&.v=1630640992000',
        price:329,
        id:704,
        color1:'graphite circle',
        color2:'gray circle',
        image1:'https://i.postimg.cc/RCtH4qvL/ipad-Classic.png',
        category:'iPad',
        stock:10,
        imageCart:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-2021-hero-silver-wifi-select?',

        chipImg:'https://i.postimg.cc/8PwnDfT9/A14-Bionic.png',
        chip:'A14 Bionic',
        screen:"10.2''",
        screenDesc:'Retina Display',
        cameraImg:'https://i.postimg.cc/0Qgyxdm0/Camera-Ipad1.png',
        camera:'8 MP | Telephoto',
        battery:'Up to 10 hours of video playback',
        chargerImg:'https://i.postimg.cc/QxvLvnhV/Charge-Ipad-Low.png',
        charger:'Lighting connector',

        classStorage3:'hide',
        classStorage4:'hide',
        storage1:'64GB',
        storage2:'128GB',
    },
    {
        new:'',
        name:"iPad Mini",
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-card-40-ipad-mini-202109?wid=400&hei=500&fmt=p-jpg&qlt=95&.v=1630457637000',
        price:329,
        id:705,
        color1:'graphite circle',
        color2:'pink circle',
        color3:'purple circle',
        color4:'gold circle',
        image1:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-mini-select-wifi-purple-202109?wid=470&hei=556&fmt=png-alpha&.v=1629840735000',
        category:'iPad',
        stock:10,
        imageCart:'https://i.postimg.cc/V6B0tdYQ/ipad-Mini-Cart.png',

        chipImg:'https://i.postimg.cc/63kfpRcx/A15-Bionic.png',
        chip:'A15 Bionic',
        screen:"8.3''",
        screenDesc:'Liquid Retina Display',
        cameraImg:'https://i.postimg.cc/0Qgyxdm0/Camera-Ipad1.png',
        camera:'12 MP | Wide camera',
        battery:'Up to 10 hours of video playback',
        chargerImg:'https://i.postimg.cc/vH4FqdRp/Charge-Ipad-Mid.png',
        charger:'USB-C connector',

        classStorage3:'hide',
        classStorage4:'hide',
        storage1:'64GB',
        storage2:'128GB',
    },
]

export default data;